### ISSUE TITLE
Long-term statistics

### ISSUE THREAD

**Issue by kputnam** [natekspencer/hacs-govee_ble#5]
Is there any plan to support the long-term statistics feature in Home Assistant? It seems to provide a way to summarize time series data at various levels of granularity, like min/max/avg value per day, week, month, etc.

More information:
* https://data.home-assistant.io/docs/statistics
* https://www.home-assistant.io/integrations/statistics
* https://www.home-assistant.io/lovelace/statistics-graph
* https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by natekspencer** [comment]
I'm working on adding this now.

**Comment by natekspencer** [comment]
Release 2021.12.0 should enable this. Let me know!
